version: 2.1

executors:
  java-executor:
    docker:
      - image: maven:3.8.6-openjdk-17
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout

      - restore_cache:
          key: maven-cache-{{ checksum "pom.xml" }}

      - run:
          name: Set JAVA_HOME
          command: echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache-{{ checksum "pom.xml" }}

      - run:
          name: Build with Maven
          command: mvn clean install

      - run:
          name: Run tests
          command: mvn test

      - store_artifacts:
          path: target/
          destination: jar-files

      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build