version: 2.1

executors:
  java-executor:
    docker:
      - image: maven:3.8.6-openjdk-11  # This image already has Maven and OpenJDK
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Pulls your repo
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build
