version: 2.1

executors:
  java-executor:
    docker:
      - image: maven:3.8.6-openjdk-11  # Base image with Maven and OpenJDK 11
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Pulls your repo
      - run:
          name: Install OpenJDK 17
          command: |
            apt-get update && apt-get install -y openjdk-17-jdk
            java -version  # Verify the installation
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build