version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Update package list
          command: sudo apt-get update
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build