version: 2.1

executors:
  java-executor:
    docker:
      - image: maven:3.8.6-openjdk-23  # Use OpenJDK 23 (if available)
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Pulls your repo
      - run:
          name: Set JAVA_HOME
          command: echo "export JAVA_HOME=/usr/lib/jvm/java-23-openjdk" >> $BASH_ENV
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build